spring.application.name=Terapias
# Datos de conexión a la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/centro_terapeutico
spring.datasource.username=admin_app
spring.datasource.password=AdminAppSeguro2024!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate/JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuración del dialecto de MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
